-- MySQL Script generated by MySQL Workbench
-- Sun Sep  7 18:52:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Semester` ;

CREATE TABLE IF NOT EXISTS `Semester` (
  `id_semester` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id_semester`),
  UNIQUE INDEX `unique_semester` (`year` ASC, `number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Course` ;

CREATE TABLE IF NOT EXISTS `Course` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_course`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseInSemester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseInSemester` ;

CREATE TABLE IF NOT EXISTS `CourseInSemester` (
  `Semester_id_semester` INT NOT NULL,
  `Course_id_course` INT NOT NULL,
  PRIMARY KEY (`Semester_id_semester`, `Course_id_course`),
  INDEX `fk_CourseInSemester_Course1_idx` (`Course_id_course` ASC) VISIBLE,
  CONSTRAINT `fk_CourseInSemester_Semester`
    FOREIGN KEY (`Semester_id_semester`)
    REFERENCES `Semester` (`id_semester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CourseInSemester_Course1`
    FOREIGN KEY (`Course_id_course`)
    REFERENCES `Course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Assessment` ;

CREATE TABLE IF NOT EXISTS `Assessment` (
  `id_assessment` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `question_amount` INT NULL,
  `id_semester` INT NOT NULL,
  `id_course` INT NOT NULL,
  PRIMARY KEY (`id_assessment`),
  INDEX `fk_Assessment_CourseInSemester1_idx` (`id_semester` ASC, `id_course` ASC) VISIBLE,
  CONSTRAINT `fk_Assessment_CourseInSemester1`
    FOREIGN KEY (`id_semester` , `id_course`)
    REFERENCES `CourseInSemester` (`Semester_id_semester` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Section` ;

CREATE TABLE IF NOT EXISTS `Section` (
  `id_section` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_semester` INT NOT NULL,
  `id_course` INT NOT NULL,
  PRIMARY KEY (`id_section`),
  INDEX `fk_Section_CourseInSemester1_idx` (`id_semester` ASC, `id_course` ASC) VISIBLE,
  CONSTRAINT `fk_Section_CourseInSemester1`
    FOREIGN KEY (`id_semester` , `id_course`)
    REFERENCES `CourseInSemester` (`Semester_id_semester` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
