-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 09:29:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Semester` ;

CREATE TABLE IF NOT EXISTS `Semester` (
  `id_semester` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `number` INT NOT NULL,
  `id_user` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `active_semester_key` VARCHAR(10) NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_semester`),
  INDEX `idx_semester_id_user` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `active_semester_key_UNIQUE` (`active_semester_key` ASC) INVISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Course` ;

CREATE TABLE IF NOT EXISTS `Course` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(10) NOT NULL,
  `id_user` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `active_code` VARCHAR(10) NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_course`),
  INDEX `idx_course_id_user` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `active_code_UNIQUE` (`active_code` ASC) VISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseInSemester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseInSemester` ;

CREATE TABLE IF NOT EXISTS `CourseInSemester` (
  `Semester_id_semester` INT NOT NULL,
  `Course_id_course` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Semester_id_semester`, `Course_id_course`),
  INDEX `fk_CourseInSemester_Course1_idx` (`Course_id_course` ASC) VISIBLE,
  INDEX `fk_CourseInSemester_Semester1_idx` (`Semester_id_semester` ASC) VISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_CourseInSemester_Semester`
    FOREIGN KEY (`Semester_id_semester`)
    REFERENCES `Semester` (`id_semester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CourseInSemester_Course1`
    FOREIGN KEY (`Course_id_course`)
    REFERENCES `Course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Assessment` ;

CREATE TABLE IF NOT EXISTS `Assessment` (
  `id_assessment` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  `number` INT NOT NULL,
  `question_amount` INT NULL DEFAULT 0,
  `id_semester` INT NOT NULL,
  `id_course` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_assessment`),
  INDEX `fk_Assessment_CourseInSemester1_idx` (`id_semester` ASC, `id_course` ASC) VISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_Assessment_CourseInSemester1`
    FOREIGN KEY (`id_semester` , `id_course`)
    REFERENCES `CourseInSemester` (`Semester_id_semester` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Section` ;

CREATE TABLE IF NOT EXISTS `Section` (
  `id_section` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `id_semester` INT NOT NULL,
  `id_course` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_section`),
  INDEX `fk_Section_CourseInSemester1_idx` (`id_semester` ASC, `id_course` ASC) VISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_Section_CourseInSemester1`
    FOREIGN KEY (`id_semester` , `id_course`)
    REFERENCES `CourseInSemester` (`Semester_id_semester` , `Course_id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Statistics` ;

CREATE TABLE IF NOT EXISTS `Statistics` (
  `id_assessment` INT NOT NULL,
  `id_section` INT NOT NULL,
  `stats` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_assessment`, `id_section`),
  INDEX `fk_Statistics_Assessment1_idx` (`id_assessment` ASC) VISIBLE,
  INDEX `fk_Statistics_Section1_idx` (`id_section` ASC) VISIBLE,
  INDEX `idx_is_deleted` (`is_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_Statistics_Assessment1`
    FOREIGN KEY (`id_assessment`)
    REFERENCES `Assessment` (`id_assessment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Section1`
    FOREIGN KEY (`id_section`)
    REFERENCES `Section` (`id_section`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
